## LAB_NO_02_Part_01_22JZELE0480 

### University of Engineering and Technology Peshawar, Nowshera Campus

#### Course: Machine Learning Lab

#### Student Name: Ibraheem khan
#### Registration Number: 22jzele0480

# Introduction to Numpy module:
NumPy is a powerful Python library for numerical computing, providing support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently. It serves as the foundation for many scientific and mathematical Python libraries due to its speed and versatility. NumPy offers capabilities for array manipulation, mathematical operations, linear algebra, random number generation, and more, making it an essential tool for data manipulation and analysis in fields such as machine learning, data science, and engineering. With its efficient implementation in C, NumPy facilitates fast computations and enables seamless integration with other Python libraries and tools. Its simplicity and performance make it a cornerstone of the Python scientific computing ecosystem.






### Installation
We can easily install this library using the terminal. Follow the steps given below to install Numpy:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install Numpy with the help of pip easily. Head over to the directory where you want to install the numpy and fire the below command:<br>
__pip install numpy__<br>
__OR__<br>
__conda install numpy__<br>
This is very simple to install. tall.

# import numpy
Once numpy is installed, import it in your applications by adding the import keyword:<br>
__import numpy as pd__<br>
Now numpy is imported and ready to use.# se.

In [6]:
import numpy as np

Recommended NumPy Topics for the Lab

1. Array creation

2. Indexing and slicing

3. Vectorized computations

4. Basic statistics

5. Reshaping/stacking

## Core NumPy Concepts & Topics Covered in this Lab:
### 1. **Array Creation:** Initializing 1D and 2D arrays from native lists and special functions.
### 2. **Indexing and Slicing:** Extracting individual elements or subarrays from 1D and 2D spaces.
### 3. **Vectorized Computations / Broadcasting:** Performing scalar-to-array and array-to-array math.
### 4. **Basic Statistics:** Computing aggregates like summation, mean, and extrema.
### 5. **Reshaping & Stacking:** Changing data dimensions without modifying underlying data.

## 1.1 Creating a 1D Array from a Python List
The simplest way to create an array is by passing a native Python list into the `np.array()` function.

In [7]:
mylist=[1,3,3,6]

# Initializing a basic Python list containing four integer values
mylist = [1, 3, 3, 6]

In [8]:
type(mylist)

list

Converting the simple list to numpy array

In [9]:
np.array(mylist)

array([1, 3, 3, 6])

### Inspecting the built-in Python data type of the 'mylist' variable
type(mylist)

In [10]:
type(mylist)

list

### 1.2 Converting the Python List to a NumPy Array
We now convert the native Python list structure into an optimized NumPy `ndarray`.

In [11]:
arr=np.array(mylist) # Assigning the newly created NumPy array to the variable 'arr' for future operations

#### Displaying the content of the newly created array arr

In [10]:
arr

array([1, 3, 3, 6])

### 1.3 Creating Matrices (2D Arrays)
A matrix is represented in NumPy as a two-dimensional array, typically constructed by passing nested Python lists (a list of lists).

In [17]:
mylist=[[1,3,5],[4,5,6],[1,4,76],[1,3,5]] # Creating a nested Python list representing a 4-row by 3-column data grid


In [12]:
mylist

[[1, 3, 5], [4, 5, 6], [1, 4, 76], [1, 3, 5]]

In [18]:
np.array(mylist) # Converting the nested Python list into a 2D NumPy array (Matrix)


array([[ 1,  3,  5],
       [ 4,  5,  6],
       [ 1,  4, 76],
       [ 1,  3,  5]])

In [19]:
mymatrix = np.array(mylist) # Storing the 2D array representation inside a variable named 'mymatrix'

In [20]:
mymatrix.shape # Checking the matrix dimensions using the .shape attribute (returns tuple: rows, columns)


(4, 3)

#### Re-instantiating the matrix into a new variable and viewing the output array directly


In [21]:
mynewmatrix = np.array(mylist)
mynewmatrix 

array([[ 1,  3,  5],
       [ 4,  5,  6],
       [ 1,  4, 76],
       [ 1,  3,  5]])

### 1.4 Generating Arrays Efficiently via Ranges using `arange`
Instead of typing lists manually, `np.arange()` generates sequences of numbers within a specified numerical interval.

In [22]:
# Generating a sequence from 0 up to (but excluding) 5
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [23]:
# Generating a sequence from 0 up to 10 with a step size of 2 (extracts even numbers)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## 1.5 Generating Constant Arrays (Zeros and Ones)
NumPy provides placeholders filled with `0` or `1`, which are highly useful for initializing weights in algorithmic operations or machine learning models.

In [24]:
np.zeros(5)# Creating a 1D array filled with 5 floating-point zeros


array([0., 0., 0., 0., 0.])

###  Creating the matrix of only Zeros

In [25]:
# Generating a 2D matrix with 4 rows and 10 columns completely filled with zeros
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

###  Creating the matrix of only 1

In [26]:
# Generating a 5x5 square matrix filled entirely with floating-point ones
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 1.6 Vectorized Arithmetic on Constant Placeholders
Applying scalar values directly to arrays demonstrates NumPy's element-wise operation power.

In [27]:
# Creating a 5x5 ones matrix and performing element-wise scalar addition of 5
np.ones((5, 5)) + 5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [28]:
# Creating a 1D array of four ones and magnifying all elements by a factor of 100
np.ones(4) * 100

array([100., 100., 100., 100.])

In [29]:
# Dividing an array of four ones by 100 to yield element-wise decimal ratios
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

### 1.7 Creating of array by using linespace function 
The general syntax of numpy.linspace() is numpy.linspace(start, stop, num=50). It generates an array of evenly spaced numbers over a specified interval [start, stop], inclusive of both endpoints, with the number of elements determined by num.

In [30]:
# Splitting the range 0 to 10 into 5 evenly spaced intervals
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
# Calculating the total number of items returned when splitting an interval into 20 segments
len(np.linspace(0, 10, 20))

20

### 1.8 Eye function 

A function with 1 on the priciple diagnol

In [32]:
# Creating a 3x3 Identity Matrix (square matrix with 1s on the primary diagonal)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.9 Random numbers

In [33]:
# Generating a 1D array of 5 random floats drawn uniformly from the interval [0.0, 1.0)
np.random.rand(5)

array([0.86953351, 0.14567157, 0.69984576, 0.78972326, 0.14311706])

In [34]:
# Generating a 3-row by 5-column matrix filled with random numbers between 0 and 1
np.random.rand(3, 5)

array([[0.07632777, 0.38003332, 0.01238125, 0.96636864, 0.46341376],
       [0.84712493, 0.06795848, 0.30177565, 0.35743542, 0.61601583],
       [0.95794236, 0.00619913, 0.36953436, 0.81063924, 0.70661738]])

In [35]:
# Generating a 1D array of 5 random integers between 1 (inclusive) and 100 (exclusive)
np.random.randint(1, 100, 5)

array([58, 27, 55, 76, 71])

#### How Random Seed Works (NumPy)

np.random.seed(x) resets the random number generator to a fixed starting point.

Using the same seed → produces the same random numbers every time.

Seed affects only the next random operations after it is called.

In Jupyter Notebook, each cell continues the same random sequence.

So, if you set the seed in one cell and generate numbers in another, the result will change.

To get identical output in different cells, set the seed again before each random operation.

In [36]:
# Setting a random seed value of 24 to guarantee reproducible output distributions
np.random.seed(24)
a = np.random.rand(4)
a

array([0.9600173 , 0.69951205, 0.99986729, 0.2200673 ])

In [37]:
# Generating subsequent numbers without resetting the seed yields the next values in line
b = np.random.rand(4)
b

array([0.36105635, 0.73984099, 0.99645573, 0.31634698])

In [38]:
# Creating an array called 'arr1' consisting of 16 random integers bounded between 0 and 50
arr1 = np.random.randint(0, 50, 16)
arr1

array([35, 15, 39,  9, 18,  7, 25, 35, 45, 31, 28,  0, 12, 31, 33,  1])

In [39]:
# Verifying current flat dimensions of 'arr1' (contains 16 entries)
arr1.shape

(16,)

### 1.11 Data Manipulation via Reshaping
The `.reshape()` method modifies the layout dimensions of an array without altering actual data items, provided the product of new dimensions equals total elements.

In [40]:
# Re-organizing the flat 16-element array into a 2-Dimensional grid of 4 rows and 4 columns
arr1.reshape(4, 4)

array([[35, 15, 39,  9],
       [18,  7, 25, 35],
       [45, 31, 28,  0],
       [12, 31, 33,  1]])

# Section 2: Advanced Indexing, Slicing, and Mask Selection
This section focuses on retrieving specific scalar objects, sections, columns, and conditional rows from your structured array elements.

In [41]:
# Ensuring the NumPy package is imported smoothly for indexing operations
import numpy as np

In [42]:
# Creating an evaluation array containing integers from 0 to 10 inclusive
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# Retrieving the item located at index position 8 (the 9th item)
arr[8]

8

In [44]:
# Retrieving the item located at index position 2 (the 3rd item)
arr[2]

2

### 2.2 Slicing 1D Arrays
Slicing uses the format `[start:stop]`, extracting elements from `start` up to, but not including, `stop`.

In [45]:
arr[1:5]# Extracting values from index 1 through index 4 (stops before index 5)
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[:]# Using standard colon notation to fetch a full copy of the entire array space
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[5:]# Extracting elements from index 5 all the way to the end of the array
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
# Fetching everything starting from index 0 up to, but excluding, index position 5
arr[:5]

array([0, 1, 2, 3, 4])

In [49]:
# Grabbing a specific subset slice starting from index 4 up to index 6
arr[4:7]

array([4, 5, 6])

In [50]:
# Pulling components out starting from index position 0 through index position 5
arr[0:6]

array([0, 1, 2, 3, 4, 5])

### 2.3 Broadcasting Operations
Broadcasting allows mathematical operators to compute values across arrays of differing dimensions without creating manual loop iterations.

In [51]:
# Temporarily broadcasting a scalar addition of 100 to all elements inside the array
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [52]:
# Setting up a 2x3 Matrix 'A' alongside a 1D row vector 'b' to show vector broadcasting
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

# Array 'b' gets duplicated across matching dimensions down matrix 'A' automatically
print(A + b)

[[11 22 33]
 [14 25 36]]


In [54]:
# Verifying that addition order does not disrupt the broadcasting mechanics
print(b + A)

[[11 22 33]
 [14 25 36]]


In [55]:
# Computing element-wise division by scaling down all inputs inside 'arr' by 2
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [58]:
# Demonstrating operational precedence: divides 100 by 2 first, then adds result to 'arr'
arr + 100 / 2

array([50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60.])

In [59]:
# Applying an element-wise exponent calculation to square every value inside the array
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### 2.4 Multidimensional Indexing and Subsetting (2D Space)
In a 2D structure, coordinates can be requested using two indices: row position first, then column position (`[row, col]`).

In [60]:
# Creating a 3x3 baseline sample evaluation matrix named 'arr_2d'
arr_2d = np.array([[1, 45, 5], [2, 45, 6], [7, 8, 9]])
arr_2d

array([[ 1, 45,  5],
       [ 2, 45,  6],
       [ 7,  8,  9]])

In [61]:
# Checking row-column configuration properties of our 2D array
arr_2d.shape

(3, 3)

In [62]:
# Accessing an entire single horizontal row cleanly via index position 1 (second row)
arr_2d[1]

array([ 2, 45,  6])

In [63]:
# Accessing the first item of the second row using classic double bracket syntax
arr_2d[1][0]

2

In [64]:
# Accessing index element row 1, column 1 via double bracket method
arr_2d[1][1]

45

In [65]:
# Accessing index position row 1, column 1 efficiently using standard single comma notation
arr_2d[1, 1]

45

In [66]:
# Reprinting the complete structure to analyze section-slicing options
arr_2d

array([[ 1, 45,  5],
       [ 2, 45,  6],
       [ 7,  8,  9]])

In [67]:
# Extracting every row from the beginning up to row index 2 (excludes row index 2)
arr_2d[:2]

array([[ 1, 45,  5],
       [ 2, 45,  6]])

In [68]:
# Slicing out a sub-matrix chunk containing row indexes 0-1 and column indexes 1 to end
arr_2d[:2, 1:]

array([[45,  5],
       [45,  6]])

### 2.5 Boolean Masking & Conditional Filtering
Boolean indexing uses logical conditions to generate truth matrices that extract items that meet specific criteria.

In [69]:
# Setting up an active array from 0 to 5 for boolean assessment
arr = np.arange(6)

In [70]:
# Verifying current sequence state values
arr

array([0, 1, 2, 3, 4, 5])

In [71]:
# Generating a comparison mask array populated with True values where elements are less than 4
arr < 4

array([ True,  True,  True,  True, False, False])

In [72]:
# Evaluating which specific elements pass the logical test of being strictly greater than 4
arr > 4

array([False, False, False, False, False,  True])

## Condition seletion 
## 2.6 Applying a Condition-Based Mask Filter

In [73]:
# Capturing the condition logical map directly into a mask variable named 'bool_arr'
bool_arr = arr > 4

In [74]:
# Outputting the truth configuration mapping array
bool_arr

array([False, False, False, False, False,  True])

In [75]:
# Extracting elements from 'arr' where 'bool_arr' evaluates to True
arr[bool_arr]

array([5])

In [76]:
# Executing conditional data selection directly inside the brackets for cleaner syntax
arr[arr > 4]

array([5])

In [77]:
# Filtering elements to match equality conditions
arr[arr == 2]

array([2])

In [78]:
# Filtering elements to match less than or equal boundaries
arr[arr <= 4]

array([0, 1, 2, 3, 4])

### 2.7 High-Level Universal Mathematical Functions (ufuncs)
NumPy provides optimized mathematical functions that execute element-wise operations across datasets.

In [79]:
# Initializing an active tracking array with standard squares
arr = np.array([1, 4, 9])

In [108]:
np.sqrt(arr)

array([1., 2., 3.])

In [109]:
np.log(arr) #bcz first no is zro its makes it infinity

array([0.        , 1.38629436, 2.19722458])

In [80]:
# Calculating trigonometric sine values element-wise for items in the array
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849])

In [111]:
arr.sum()

np.int64(14)

In [112]:
arr.max()

np.int64(9)

In [81]:
# Calculating the statistical arithmetic mean average of your array content
arr.mean()

4.666666666666667

In [114]:
arr_2d=np.array([[1,2,3],[2,2,3],[4,1,1]])

In [115]:
arr_2d

array([[1, 2, 3],
       [2, 2, 3],
       [4, 1, 1]])

In [116]:
arr_2d.sum()

np.int64(19)

In [117]:
arr_2d.shape

(3, 3)

In [85]:
# give me sum acroos the rows
arr_2d.sum(axis=0) 
    #array  along the vertical axis when axis=0 that count colum element
  #mean that produce the sum of the coluam  

array([7, 5, 7])

In [86]:
arr_2d.sum(axis=1)

array([6, 7, 6])

# 3 NumPy Statistical Functions

In [87]:
import numpy as np

arr = np.array([4, 9, 2, 7, 5])
print("Array:", arr)

# Mean
print("Mean:", arr.mean())

# Maximum value
print("Max:", arr.max())

# Minimum value
print("Min:", arr.min())

# Index of maximum value
print("Argmax:", arr.argmax())

# Index of minimum value
print("Argmin:", arr.argmin())

# Standard deviation
print("Standard Deviation:", arr.std())

# Variance
print("Variance:", arr.var())

# Median
print("Median:", np.median(arr))

# Sum of all elements
print("Sum:", arr.sum())

# Cumulative sum
print("Cumulative Sum:", arr.cumsum())

# Sorting
print("Sorted Array:", np.sort(arr))


Array: [4 9 2 7 5]
Mean: 5.4
Max: 9
Min: 2
Argmax: 1
Argmin: 2
Standard Deviation: 2.4166091947189146
Variance: 5.84
Median: 5.0
Sum: 27
Cumulative Sum: [ 4 13 15 22 27]
Sorted Array: [2 4 5 7 9]


## numpy exericses 

In [88]:
import numpy as np

## create an array of 10 zeros

In [89]:
arr=np.zeros(10)

In [90]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## create an array of 10 ones

In [91]:
arr=np.ones(10)

In [92]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## create an array of 10 fives 

In [93]:
arr=np.ones(10)*5

In [94]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## create an array of  integer  from 10 to 50

In [95]:
arr=np.arange(10,51)

In [96]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

## create an array of all even integer from 10 to 50

In [97]:
arr=np.arange(10,51,2)

In [98]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## create 3x3 matrix with the values ranging of 0 to 8

In [99]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [100]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
matrix = np.arange(9).reshape((3, 3))

In [102]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [103]:
matrix = np.arange(16)
matrix.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## create 3x3 identity matrix

In [104]:
identity_matrix = np.identity(3)
identity_matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [106]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
arr=np.random.rand(1)

In [108]:
arr

array([0.53503753])

In [109]:
random_matrix = np.random.randn(25)

In [110]:
random_matrix

array([-0.05813086,  0.58860351,  0.79823053, -1.94995143, -2.1628745 ,
        0.1732177 ,  0.44980691, -0.15639909, -0.5017551 , -1.13070873,
       -2.29896186,  0.69752566, -1.17402782, -0.73272521, -1.984332  ,
        0.26950264, -0.77941255,  0.8706628 , -0.32149986,  1.9582427 ,
        1.79617509,  1.352329  , -0.38124668,  0.36649793,  0.99719722])

In [111]:
arr=np.arange(1,101)

In [112]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [113]:
arr=np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [114]:
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

## create an arry of 20 linearly spaced point b/w 0 and 1

In [115]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## numpy indexing and selection

In [116]:
mat=np.arange(1,26).reshape(5,5)

In [117]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [118]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [119]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [120]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [121]:
mat[3,4]

np.int64(20)

In [122]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [123]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [124]:
mat.sum()

np.int64(325)

In [125]:
mat.std()

np.float64(7.211102550927978)

In [126]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [127]:
np.random.seed(101)

In [128]:
np.random.rand(1)

array([0.51639863])